# Generated by Django 5.0.6 on 2024-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_room_max_players_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='loser_rule',
            field=models.IntegerField(default=4),
        ),
    ]
