# Generated by Django 5.0.6 on 2024-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_room_loser_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_amount',
            field=models.IntegerField(default=10),
        ),
    ]
