# Generated by Django 5.0.6 on 2024-06-16 08:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_room_game_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_max_players', models.IntegerField(default=4)),
                ('room_loser_rule', models.IntegerField(default=4)),
                ('room_game_amount', models.IntegerField(default=10)),
                ('date_time', models.DateTimeField()),
                ('commision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('losers', models.ManyToManyField(blank=True, related_name='losers', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.room')),
                ('room_players', models.ManyToManyField(blank=True, related_name='room_players', to=settings.AUTH_USER_MODEL)),
                ('winners', models.ManyToManyField(blank=True, related_name='winners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
