# Generated by Django 5.0.6 on 2024-06-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_roombase_room_roombase_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombase',
            old_name='commision',
            new_name='commission',
        ),
    ]
