# Generated by Django 5.0.6 on 2024-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
