# Generated by Django 5.0.6 on 2024-06-15 11:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mainuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
