# Generated by Django 5.0.6 on 2024-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mainuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='loserate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='tokenslose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='tokenswin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='winrate',
            field=models.IntegerField(default=0),
        ),
    ]
