# Generated by Django 5.0.6 on 2024-06-15 16:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mainuser_loserate_mainuser_tokenslose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='tokenslose',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='tokenswin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
