# Generated by Django 5.0.6 on 2024-06-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mainuser_tokenslose_alter_mainuser_tokenswin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='deposits',
            field=models.IntegerField(default=0),
        ),
    ]
